FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# banking

This is a banking API Catalog Examplee
API allowing consumers to do banking query transactions.

## Banking Collection [/ConsultarSaldo]

This is the main entrance to allow users to interact with API bank operational site

### IsAlive [GET]

+ Request (application/json)

+ Response 201 (application/json)
    
    + Body
        { 
            "status":"OK"
        }

### ConsultarSaldo [POST]

+ Request (application/json)

    + Headers

            control-Id: 123123123
    
    + Body
            
            {
                "Query": {
                        "clientId": "90807060",
                        "acountId": 91817161,
                        "authorizationKey": "asdfasdfiouwef38rQOWIEJ493QNUFOJAWOCFJKDSF"
                    }
            }

+ Response 201 (application/json)

    + Headers

            correlationId: 92827262

    + Body

            {
                "response": {
                        "mount": 1500,
                        "currency": "CLP",
                        "location": "agustinas"
                    }
            }