FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# banking

API allowing consumers to do banking deposit transactions.

## Banking Collection [/CargoAbonoMDPService_WS]

### Realizar Deposito [POST]

+ Request (application/json)

    + Headers

            X-IBM-Client-Id: 123123123
    
    + Body

            {
                "Security": 
                    {
                        "UsernameToken": 
                            {
                                "Username": "pocuser",
                                "Password": "abcpw"
                            }
                    }
            }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
              "GENERICFINANCIALSERVICE_IN": {
                "CANAL": "canal",
                "SUCURSAL": "001",
                "MODOTRX": "D",
                "MODOINVOCACION": "S",
                "RUTCLIENTE": "111111111",
                "TRACENUMBER": "22222222",
                "FECHACONTABLE": "20181125",
                "MONEDACARGO": "CLP",
                "BANCOCARGO": "999",
                "CUENTACARGO": "123456",
                "TIPOCUENTACARGO": "00001",
                "MONTOCARGO": "100",
                "TIPOCUENTABONO": "0000",
                "IDSERVICIO": "abonoservice",
                "REFERENCIA": "POC API Oracle",
                "DOCABONO": "12345"
              }
            }